### ISSUE TITLE
Need to change some VR params

### ISSUE THREAD

**Issue by mmmorimoto** [amansaleem/SaleemLab-VR#32]
- [x] Lower the contrast of background
- [x] Change sf of the main textures
- [x] Remove 'wheel to VR'

**Comment by amansaleem** [comment]
removed wheel to VR

**Comment by amansaleem** [comment]
This is done. Just use create_textures function to make a new texture. Is is in NewServer and NewServer_dev branches. 
First three lines have the options

texsize = 512;
wn_contrast = 1;
sf = 12; % no.of bars visible
